name: Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: cd client
      - run: npm ci
      - run: npm run build
